# Generated by Django 4.1.4 on 2023-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_image_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
