# Generated by Django 4.1.4 on 2023-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_posttag_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreaction',
            name='dislike',
        ),
        migrations.AddField(
            model_name='userreaction',
            name='reaction',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20),
        ),
    ]
